package com.draco18s.harderfarming.integration;

import com.draco18s.hardlib.api.HardLibAPI;
import com.draco18s.hardlib.api.internal.CropWeatherOffsets;

import net.minecraft.block.Block;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

public class IntegrationHarvestcraft {
	public static void registerCrops() {
		Block b;
		CropWeatherOffsets off;
		//nether
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamblackberryCrop"));
		off = new CropWeatherOffsets(-0.3f,0.5f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamblueberryCrop"));
		off = new CropWeatherOffsets(0.0f,0.0f,0.25f,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcandleberryCrop"));
		off = new CropWeatherOffsets(-0.4f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamraspberryCrop"));
		off = new CropWeatherOffsets(0.2f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamstrawberryCrop"));
		off = new CropWeatherOffsets(-0.3f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcactusfruitCrop"));
		off = new CropWeatherOffsets(-0.6f,0.6f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamasparagusCrop"));
		off = new CropWeatherOffsets(0.0f,0.4f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambarleyCrop"));
		off = new CropWeatherOffsets(0.4f,0.0f,0,-0.25f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamoatsCrop"));
		off = new CropWeatherOffsets(0.4f,-0.6f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamryeCrop"));
		off = new CropWeatherOffsets(0.4f,0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcornCrop"));
		off = new CropWeatherOffsets(0.0f,0.0f,-1f/6f,-1f/6f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambambooshootCrop"));
		off = new CropWeatherOffsets(-0.4f,-0.4f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcantaloupeCrop"));
		off = new CropWeatherOffsets(-0.4f,0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcucumberCrop"));
		off = new CropWeatherOffsets(-0.1f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamwintersquashCrop"));
		off = new CropWeatherOffsets(0.8f,0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamzucchiniCrop"));
		off = new CropWeatherOffsets(0.1f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambeetCrop"));
		off = new CropWeatherOffsets(0.3f,-0.3f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamonionCrop"));
		//-0.2 to offset the season-cycle making summer hot.  Cold season crop
		off = new CropWeatherOffsets(-0.2f,0.0f,0.5f,0.5f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamparsnipCrop"));
		off = new CropWeatherOffsets(0.2f,0.0f,0.25f,0.25f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pampeanutCrop"));
		off = new CropWeatherOffsets(-0.6f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamradishCrop"));
		off = new CropWeatherOffsets(0.6f,0.0f,0,-0.25f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamrutabagaCrop"));
		off = new CropWeatherOffsets(0.0f,-0.2f,0.5f,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamsweetpotatoCrop"));
		off = new CropWeatherOffsets(-0.5f,-0.5f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamturnipCrop"));
		off = new CropWeatherOffsets(0.2f,0.3f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamrhubarbCrop"));
		off = new CropWeatherOffsets(0.25f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamceleryCrop"));
		off = new CropWeatherOffsets(0.4f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamgarlicCrop"));
		off = new CropWeatherOffsets(0.2f,-0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamgingerCrop"));
		off = new CropWeatherOffsets(-0.2f,-0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamspiceleafCrop"));
		off = new CropWeatherOffsets(-0.2f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamtealeafCrop"));
		off = new CropWeatherOffsets(-0.2f,-0.3f,-1f/12f,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcoffeebeanCrop"));
		off = new CropWeatherOffsets(-0.4f,-0.4f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pammustardseedsCrop"));
		off = new CropWeatherOffsets(-0.6f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambroccoliCrop"));
		off = new CropWeatherOffsets(0.2f,-0.2f,0,-0.25f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcauliflowerCrop"));
		off = new CropWeatherOffsets(0.2f,-0.1f,0,-1f/3f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamleekCrop"));
		off = new CropWeatherOffsets(0.3f,0.0f,1f/6f,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamlettuceCrop"));
		off = new CropWeatherOffsets(0.2f,0.2f,0,-1f/3f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamscallionCrop"));
		off = new CropWeatherOffsets(0.2f,-0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamartichokeCrop"));
		off = new CropWeatherOffsets(-0.2f,0.5f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambrusselsproutCrop"));
		off = new CropWeatherOffsets(0.3f,0.0f,-1f/6f,-1f/6f);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcabbageCrop"));
		off = new CropWeatherOffsets(0.9f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamspinachCrop"));
		off = new CropWeatherOffsets(0.7f,-0.2f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamwhitemushroomCrop"));
		off = new CropWeatherOffsets(-0.3f,-0.3f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambeanCrop"));
		off = new CropWeatherOffsets(0.0f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamsoybeanCrop"));
		off = new CropWeatherOffsets(0.0f,-0.25f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pambellpepperCrop"));
		off = new CropWeatherOffsets(-0.3f,-0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamchilipepperCrop"));
		off = new CropWeatherOffsets(-0.5f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pameggplantCrop"));
		off = new CropWeatherOffsets(-0.4f,0.3f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamokraCrop"));
		off = new CropWeatherOffsets(-0.2f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pampeasCrop"));
		off = new CropWeatherOffsets(0.2f,0.3f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamtomatoCrop"));
		off = new CropWeatherOffsets(-0.4f,0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcottonCrop"));
		off = new CropWeatherOffsets(-0.6f,0.3f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pampineappleCrop"));
		off = new CropWeatherOffsets(-0.6f,0.6f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamgrapeCrop"));
		off = new CropWeatherOffsets(-0.3f,-0.1f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamkiwiCrop"));
		off = new CropWeatherOffsets(0.3f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamcranberryCrop"));
		off = new CropWeatherOffsets(0.0f,-0.5f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamriceCrop"));
		off = new CropWeatherOffsets(-0.2f,-0.8f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);
		b = ForgeRegistries.BLOCKS.getValue(new ResourceLocation("harvestcraft:pamseaweedCrop"));
		off = new CropWeatherOffsets(0.2f,0.0f,0,0);
		HardLibAPI.hardCrops.putCropWeather(b, off);

	}
}